# % YAML 1.2
---
port: 8081 #A port amin a backend fut
dsn: # Adatbázis kapcsolódáshoz szükséges konfiguráció
  host: localhost
  user: username
  password: password
  dbname: dbname
  port: 5432
smtp: # SMTP szerver kapcsolódáshoz szükséges konfiguráció
  host: mail.smtp2go.com # smtp2go.com ingyenes SMTP regisztálható
  port: 2525
  sender: sender@mail.mail # Az smtp szerverről küldött email feladója
  username: smtpusername
  password: smtppassword
frontend: # A frontend hálózati helyének konfigurációja, a megadott értékek a vite preview alapértelmezései
  host: localhost
  port: 4173
geolocation_api_key: apikey # https://geocode.maps.co/ oldalról lehet kulcsot igényelni
jwt_secret_key: 02dd313e36caf1151b0e3ff9319bd4799e73e1f561c7c364676b033b424d7118 # Tetszőleges 64 karakter hosszú, hex kódolt 256-bites AES kulcs
email_dev: false # Ha igaz, akkor nem szükséges smtp beállításokat megadni
pricing_dev: false # Ha igaz, akkor kell nem geolocation_api_keyt megadni
